name: Frontend CDK Synth
description: Build frontend (optionally) and synthesize CDK templates

inputs:
  environment:
    description: 'Deployment environment (dev, staging, prod)'
    required: true
  should-build:
    description: 'Whether to build the frontend before synth'
    required: false
    default: 'false'
  api-url:
    description: 'Backend API URL for frontend build'
    required: false
    default: ''
  user-pool-id:
    description: 'Cognito User Pool ID for frontend build'
    required: false
    default: ''
  user-pool-client-id:
    description: 'Cognito User Pool Client ID for frontend build'
    required: false
    default: ''
  domain-name:
    description: 'Domain name for the application'
    required: false
    default: ''
  hosted-zone-id:
    description: 'Route53 hosted zone ID'
    required: false
    default: ''
  hosted-zone-name:
    description: 'Route53 hosted zone name'
    required: false
    default: ''
  certificate-arn:
    description: 'ACM certificate ARN'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Build frontend
      if: inputs.should-build == 'true'
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        VITE_API_URL: ${{ inputs.api-url }}
        VITE_USER_POOL_ID: ${{ inputs.user-pool-id }}
        VITE_USER_POOL_CLIENT_ID: ${{ inputs.user-pool-client-id }}
      run: npx nx build photos-fe

    - name: Synthesize CDK
      shell: bash
      working-directory: apps/photos-fe
      run: |
        if [[ -n "${{ inputs.domain-name }}" ]]; then
          echo "Synthesizing with domain configuration..."
          npx cdk synth \
            --context environment=${{ inputs.environment }} \
            --context domainName=${{ inputs.domain-name }} \
            --context hostedZoneId=${{ inputs.hosted-zone-id }} \
            --context hostedZoneName=${{ inputs.hosted-zone-name }} \
            --context certificateArn=${{ inputs.certificate-arn }}
        else
          echo "Synthesizing with environment only..."
          npx cdk synth --context environment=${{ inputs.environment }}
        fi
